### ISSUE TITLE
Create commit status

### ISSUE THREAD

**Issue by vsaveliev** [k8s-community/github-integration#2]
Screenshot:
https://yadi.sk/i/bVhMapkh3JBejr

Docs:
https://developer.github.com/v3/repos/statuses/

**Comment by vsaveliev** [comment]
Мне почему-то кажется, что надо использовать oauth внутри integration. И авторизацию в GitHub-integration добавлять.

Хуки принимать можно и без всякой авторизации, а вот статус обновлять - нет.

**Comment by rumyantseva** [comment]
Заветная галочка 👍 

Я хочу оставить oauth и отдельным тоже. Нормальный юз-кейс -- это про то, что пользователь сначала заходит на лендинг-страницу и авторизуется. Кейс про то, что сначала он идет в интеграцию, возможен, но он нетипичный (он возможен только если пользователь захочет сделать всё не по инструкции).
